version: "3.7"

services:
  web:
    build: .
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 3009:8080
    volumes:
      - ./home:/home/coder
    environment:
      PASSWORD: moneyprintergobrrr
